[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1"
clap = { version = "4.1", features = ["derive"] }
aya-tool = { git = "https://github.com/aya-rs/aya" }
